### PR TITLE
Caching mapper changes

### PR DESCRIPTION
**Pull request by matthiasdiener**
This is ready for review @kaushikcfd

### CODE REVIEW

**Comment by inducer** [comment]
Would this apply to `main`? If so, want to pitch it there?

**Comment by matthiasdiener** [comment]
> Would this apply to `main`? If so, want to pitch it there?

No, these are specific to Kaushik's additional mappers in his main

**Comment by kaushikcfd** [comment]
Thank you, I'll pull these into the correct PR's branch.

**Comment by kaushikcfd** [comment]
Thanks once again!
I have pulled these commits into `main`, and their corresponding PRs:
- https://github.com/inducer/loopy/pull/493
- https://github.com/inducer/loopy/pull/267

**Comment by matthiasdiener** [comment]
Thank you!

**Pull request closed without merging**
